[[constraint]]
  name = "github.com/sarulabs/di"
  version = "2.1.0"
[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"
[[constraint]]
  name = "github.com/sevlyar/go-daemon"
  version = "0.1.4"
[[constraint]]
  name = "github.com/stevenroose/gonfig"
  version = "0.1.1"
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
[[constraint]]
  name = "gonum.org/v1/plot"
  revision = "0582252c54f67a656af44d054ca37602364139eb"